### ISSUE TITLE
Import into updatesite

### ISSUE THREAD

**Issue by TomVanAken** [jesse-gallagher/nsf-router#1]
I wanted to import the site.xml into an update site (Notes Client v12.0.2 64bit) and got this error
![image](https://user-images.githubusercontent.com/13216596/202487440-f447e762-c9b9-4388-a774-775db28bc88c.png)

**Comment by jesse-gallagher** [comment]
Huh, that's ominous. I don't think it's related to this project, though - that's coming from the importer agent, and it makes me wonder if the 64-bit client doesn't ship with an appropriate SWT implementation in the classpath the same way the 32-bit one does.

**Comment by TomVanAken** [comment]
Just saw that Karsten Lehman created a new updateSite template for 64bit. I will check if that fixes the issue.

**Comment by perlausten** [comment]
> Just saw that Karsten Lehman created a new updateSite template for 64bit. I will check if that fixes the issue.

It does 😄
